"""Gold stock-transfer monitor — desktop build, adapted for Session 3 Part A.

Adaptation (Aaron Sapkota, 36104 DVN):
  - question added: "When did a country buy or sell, and how does that line
    up with the marked events and with another country?" The 12-month
    ranking answers who bought most; the new explorer at the end of the
    Declared tab answers when. It has a country picker, an optional second
    country, a month-range control, and a monthly / running-total switch.
  - every page area says the figures are sample data (generated by
    ingest.py --synthetic), not real market data.
  - colours no longer force a light page, so Streamlit's Light / Dark
    theme menu works. The top-right menu is visible again for that.

Run:  python ingest.py --synthetic   (once, or --all for live data)
      streamlit run app.py

Design contract (reasoning in the companion notebook):
  - solid = reported, dashed = estimated; one colour per country everywhere
  - the same event rules on every time axis; labels only on the dominant charts
  - one bordered region (the KPI strip); whitespace does all other grouping
  - one dominant chart per tab: P1 carries Declared, P4 carries Inferred
"""
from pathlib import Path
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import streamlit as st

import design as dz

DATA = Path(__file__).parent / "data"

st.set_page_config(page_title="Gold stock-transfer monitor",
                   layout="wide", initial_sidebar_state="collapsed")

# ---------------------------------------------------------------- chrome/css --
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;1,6..72,400;1,6..72,500&family=Archivo:wght@400;500;600&display=swap');

html, body, [class*="css"], .stMarkdown, p, li {
  font-family: 'Archivo', system-ui, sans-serif;
  font-variant-numeric: tabular-nums;
}
.block-container { max-width: 1180px; padding-top: 2.2rem; padding-bottom: 3rem; }
footer { visibility: hidden; }
header[data-testid="stHeader"] { background: transparent; }

h1 { font-family: 'Newsreader', serif; font-weight: 500; letter-spacing: -.01em;
     font-size: 2.5rem; margin-bottom: 0; }
h3 { font-family: 'Newsreader', serif; font-style: italic; font-weight: 500;
     font-size: 1.35rem; margin-bottom: 0; }
.stCaption, [data-testid="stCaptionContainer"] { color: #8c8c84; }

/* tabs: underline grammar, gold for the active page */
.stTabs [data-baseweb="tab-list"] { gap: 30px; border-bottom: 1px solid #ecece5; }
.stTabs [data-baseweb="tab"] { font-size: 15px; font-weight: 500; color: #8c8c84;
  padding: 6px 0 10px; background: none; }
.stTabs [aria-selected="true"] { color: inherit; }
.stTabs [data-baseweb="tab-highlight"] { background-color: #a3780a; height: 2px; }
.stTabs [data-baseweb="tab-border"] { background-color: transparent; }

/* KPI strip: the only bordered region on the page */
.kpis { border: 1.5px solid rgba(128,128,128,.65); border-radius: 3px;
  display: grid; gap: 8px 26px;
  /* six tiles in a row on a wide screen; wraps on narrow screens instead
     of spilling past the border */
  grid-template-columns: repeat(auto-fit, minmax(135px, 1fr));
  padding: 14px 18px 10px; margin: 6px 0 4px; }
.kpi .l { font-size: 11px; color: #8c8c84; line-height: 1.25; }
.kpi .v { font-size: 20px; font-weight: 600; margin-top: 1px; }
.kpi .v small { font-size: 11.5px; font-weight: 500; color: #8c8c84; margin-left: 4px; }
.kpi svg { display: block; margin-top: 4px; }

.grammar { font-size: 12.5px; color: #8c8c84; margin: 2px 0 10px; }
.grammar b { color: inherit; font-weight: 500; }
.masthead { display: flex; justify-content: space-between; align-items: baseline; }
.masthead .d { color: #8c8c84; font-size: 13px; text-align: right; }
.sample { display: inline-block; font-size: 11.5px; font-weight: 600;
  letter-spacing: .04em; text-transform: uppercase; color: #a3780a;
  border: 1px solid #a3780a; border-radius: 3px; padding: 2px 7px;
  margin: 2px 0 6px; }
.facts { font-size: 13px; color: #8c8c84; margin: 0 0 2px; }
.facts b { color: inherit; font-weight: 600; }
</style>
""", unsafe_allow_html=True)

# ------------------------------------------------------------- plotly theme --
# No background or text colour is fixed here: st.plotly_chart's default
# Streamlit theme fills those in for whichever theme the reader picks.
pio.templates["ledger"] = go.layout.Template(layout=dict(
    font=dict(family="Archivo, system-ui, sans-serif", size=13),
    margin=dict(l=10, r=64, t=34, b=10), showlegend=False,
    xaxis=dict(showgrid=False, ticks="outside", tickcolor=dz.GHOST,
               linecolor=dz.GHOST),
    yaxis=dict(gridcolor=dz.GRID, zeroline=False, side="right",
               tickformat=","),
    hoverlabel=dict(bgcolor=dz.PAPER, bordercolor=dz.GHOST,
                    font=dict(family="Archivo, system-ui, sans-serif",
                              color=dz.INK, size=12)),
))
pio.templates.default = "ledger"

# ------------------------------------------------------------------ loading --
@st.cache_data(ttl=3600)
def load(name: str, dates=("date",)) -> pd.DataFrame:
    return pd.read_csv(DATA / f"{name}.csv", parse_dates=list(dates))

try:
    price = load("price")
    etf = load("etf")
    declared = load("declared")
    gap = load("gap", dates=("quarter_end",))
    swiss = load("swiss")
except FileNotFoundError:
    st.error("No data found. Run `python ingest.py --synthetic` first.")
    st.stop()

asof = {"price": price.date.max(), "etf": etf.date.max(),
        "declared": declared.date.max(), "gap": gap.quarter_end.max(),
        "swiss": swiss.date.max()}
fmt = lambda t: pd.Timestamp(t).strftime("%b %y")

# --------------------------------------------------------------- helpers -----
def events(fig, label: bool):
    for i, (d, t) in enumerate(dz.EVENTS):
        fig.add_vline(x=d, line_color=dz.RULE, line_width=1)
        if label:
            fig.add_annotation(x=d, y=1.03 + 0.075 * (i % 2), yref="paper",
                               text=t, showarrow=False,
                               font=dict(size=11, color=dz.FAINT))

def endlabel(fig, x, y, text, color=dz.FAINT):
    fig.add_annotation(x=x, y=y, text=text, showarrow=False, xanchor="left",
                       xshift=8, font=dict(size=12, color=color))

def chart(fig, h):
    fig.update_layout(height=h)
    st.plotly_chart(fig, width="stretch",
                    config={"displayModeBar": False})

def spark(vals, color, w=76, h=20):
    lo, hi = min(vals), max(vals) + 1e-9
    pts = " ".join(f"{2 + (w-4)*i/(len(vals)-1):.1f},"
                   f"{h-2 - (h-4)*(v-lo)/(hi-lo):.1f}" for i, v in enumerate(vals))
    return (f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
            f'<polyline points="{pts}" fill="none" stroke="{color}" '
            f'stroke-width="1.6" stroke-linejoin="round"/></svg>')

# ------------------------------------------------------------- derived nums --
t12 = (declared[declared.date > asof["declared"] - pd.DateOffset(months=12)]
       .groupby("country").net_purchases_t.sum().sort_values(ascending=False))
top_buy, top_sell = t12.index[0], t12.index[-1]
east_m = (swiss[swiss.destination.isin(["China + HK", "India", "Turkey"])]
          .groupby("date").tonnes.sum())
all_last = swiss[swiss.date == asof["swiss"]].tonnes.sum()
gap_res = (gap.wgc_estimate_t - gap.imf_reported_t)
p_now, p_prev = price.price_usd_oz.iloc[-1], price.price_usd_oz.iloc[-2]
e_now, e_prev = etf.tonnes.iloc[-1], etf.tonnes.iloc[-2]
china12 = declared[declared.country == top_buy].net_purchases_t.tail(12)
russia12 = declared[declared.country == top_sell].net_purchases_t.tail(12)

# ----------------------------------------------------------------- masthead --
st.markdown(f"""
<div class="masthead"><h1>Gold stock-transfer monitor</h1></div>
""", unsafe_allow_html=True)
# one label carries both facts: the figures are sample data, and the
# months they cover
sample_span = (f"{price.date.min():%b %Y} to "
        f"{pd.Timestamp(asof['price']):%b %Y}")
st.markdown(f'<span class="sample">Sample data, {sample_span} · generated for '
            f'practice, not real market figures</span>',
            unsafe_allow_html=True)
st.caption("Who holds the stock, and which way it is moving.")

KPIS = [
    ("price, $/oz", f"{p_now:,.0f}", f"{p_now/p_prev-1:+.1%} m/m",
     spark(price.price_usd_oz.tail(12).tolist(), dz.GOLD)),
    ("GLD + IAU", f"{e_now:,.0f} t", f"{e_now-e_prev:+.0f} t m/m",
     spark(etf.tonnes.tail(12).tolist(), dz.hue("West"))),
    ("gap, latest qtr", f"+{gap_res.iloc[-1]:,.0f} t", "unreported",
     spark(gap_res.tail(8).tolist(), dz.GOLD)),
    ("top buyer, 12m", top_buy, f"+{t12.iloc[0]:,.0f} t",
     spark(china12.tolist(), dz.hue(top_buy))),
    ("top seller, 12m", top_sell, f"{t12.iloc[-1]:,.0f} t",
     spark(russia12.tolist(), dz.hue(top_sell))),
    (f"Swiss → east, {fmt(asof['swiss'])}", f"{east_m.iloc[-1]:,.0f} t",
     f"of {all_last:,.0f} t out",
     spark(east_m.tail(12).tolist(), dz.hue("China"))),
]
tiles = "".join(f'<div class="kpi"><div class="l">{l}</div>'
                f'<div class="v">{v}<small>{s}</small></div>{sp}</div>'
                for l, v, s, sp in KPIS)
st.markdown(f'<div class="kpis">{tiles}</div>', unsafe_allow_html=True)
st.markdown('<p class="grammar"><b>Solid</b> marks reported series, '
            '<b>dashed</b> marks estimates. Each country keeps one colour on '
            'every panel.</p>', unsafe_allow_html=True)

tabD, tabI = st.tabs(["Declared", "Inferred"])

# ============================================================== DECLARED =====
with tabD:
    st.subheader("Price and its opportunity cost")
    st.caption(f"Has the price detached from real yields, and by how much? — "
               f"as of {fmt(asof['price'])}")
    f = go.Figure()
    f.add_trace(go.Scatter(x=price.date, y=price.yield_implied_usd_oz,
        name="yield-implied", mode="lines",
        line=dict(color=dz.MARK, width=1.4, dash=dz.DASH)))
    f.add_trace(go.Scatter(x=price.date, y=price.price_usd_oz, name="price",
        mode="lines", line=dict(color=dz.GOLD, width=2.6),
        fill="tonexty", fillcolor="rgba(163,120,10,.13)"))
    events(f, label=True)
    endlabel(f, price.date.iloc[-1], p_now, f"<b>{p_now:,.0f}</b> $/oz", dz.GOLD)
    endlabel(f, price.date.iloc[-1], price.yield_implied_usd_oz.iloc[-1], "implied")
    f.update_layout(hovermode="x unified")
    chart(f, 430)
    st.caption("Shaded wedge: actual price over the pre-2022 yield-implied "
               "level — the premium a yield-indifferent buyer pays.")

    left, right = st.columns([3, 2], gap="large")
    with left:
        st.subheader("Western investor holdings")
        st.caption(f"Is the yield-sensitive holder buying this move or "
                   f"selling into it? — as of {fmt(asof['etf'])}")
        f = go.Figure(go.Scatter(x=etf.date, y=etf.tonnes, mode="lines",
            line=dict(color=dz.hue("West"), width=2.4)))
        events(f, label=False)
        endlabel(f, etf.date.iloc[-1], e_now, f"<b>{e_now:,.0f}</b> t",
                 dz.hue("West"))
        chart(f, 330)
    with right:
        st.subheader("Declared official sector")
        st.caption(f"Trailing 12-month reported change — IMF, "
                   f"{fmt(asof['declared'])}")
        s = t12.sort_values()
        f = go.Figure(go.Bar(x=s.values, y=s.index, orientation="h",
            marker_color=[dz.hue(c) for c in s.index],
            text=[f"{v:+,.0f}" for v in s.values], textposition="outside",
            textfont=dict(size=11, color=dz.FAINT), cliponaxis=False))
        f.update_xaxes(title="tonnes", showgrid=False)
        f.update_yaxes(side="left", showgrid=False)
        chart(f, 330)

    with st.expander("12-month detail per bank"):
        d12 = declared[declared.date > asof["declared"] -
                       pd.DateOffset(months=12)].copy()
        order = t12.index.tolist()
        fig = px.bar(d12, x="date", y="net_purchases_t", facet_col="country",
                     facet_col_wrap=5, category_orders={"country": order},
                     color="country",
                     color_discrete_map={c: dz.hue(c) for c in order},
                     facet_row_spacing=.10, facet_col_spacing=.03)
        fig.update_yaxes(matches=None, title=None, side="left")
        fig.update_xaxes(title=None, showticklabels=False)
        fig.for_each_annotation(lambda a:
            a.update(text=a.text.split("=")[-1], font=dict(size=12)))
        chart(fig, 520)

    # ------------------------------------------------ adaptation: explorer --
    # The ranking above sums the last 12 months, so it shows who bought most
    # but hides when. This view puts one country's months back on a time
    # axis, with the same event rules as the other charts, and can lay a
    # second country beside it.
    st.subheader("When did each country buy or sell?")
    st.caption("Pick a country, and optionally a second one, to see the "
               "months behind the ranking above. Sample data.")

    countries = t12.index.tolist()          # ranking order: top buyer first
    months = sorted(declared.date.unique())
    c1, c2, c3 = st.columns([1, 1, 1.3], gap="medium")
    with c1:
        country = st.selectbox("Country", countries, index=0)
    with c2:
        others = ["(none)"] + [c for c in countries if c != country]
        compare = st.selectbox("Compare with", others,
                               index=others.index(top_sell)
                               if top_sell in others else 0)
    with c3:
        start, end = st.select_slider(
            "Months shown", options=months, value=(months[0], months[-1]),
            format_func=lambda t: pd.Timestamp(t).strftime("%b %Y"))
    view = st.radio("Show", ["Monthly purchases and sales",
                             "Running total over the months shown"],
                    horizontal=True)
    running = view.startswith("Running")

    picked = [country] + ([compare] if compare != "(none)" else [])
    sel = declared[declared.country.isin(picked)
                   & declared.date.between(start, end)].copy()
    sel = sel.sort_values("date")
    sel["running_t"] = sel.groupby("country").net_purchases_t.cumsum()

    # Countries without a reserved hue share the rest-of-world grey; when
    # both picks are grey, the second is drawn lighter with a hatch (bars)
    # or open markers (lines) so the two stay apart without new colours.
    cols = {c: dz.hue(c) for c in picked}
    if len(picked) == 2 and cols[picked[0]] == cols[picked[1]]:
        cols[picked[0]] = dz.MARK
    f = go.Figure()
    for i, c in enumerate(picked):
        d = sel[sel.country == c]
        second = i == 1
        if running:
            f.add_trace(go.Scatter(x=d.date, y=d.running_t, name=c,
                mode="lines+markers" if second else "lines",
                line=dict(color=cols[c], width=2.4),
                marker=dict(symbol="circle-open", size=6),
                hovertemplate=f"{c}: %{{y:+,.0f}} t so far<extra></extra>"))
            endlabel(f, d.date.iloc[-1], d.running_t.iloc[-1],
                     f"{c} <b>{d.running_t.iloc[-1]:+,.0f}</b> t", cols[c])
        else:
            f.add_trace(go.Bar(x=d.date, y=d.net_purchases_t, name=c,
                marker_color=cols[c],
                marker_pattern_shape="/" if second and
                    dz.hue(picked[0]) == dz.hue(c) else "",
                opacity=.9,
                hovertemplate=f"{c}: %{{y:+,.1f}} t<extra></extra>"))
    # the 12-month window that the ranking sums, so the two views connect
    w0 = asof["declared"] - pd.DateOffset(months=12) + pd.DateOffset(days=1)
    if pd.Timestamp(end) >= w0:
        f.add_vrect(x0=max(w0, pd.Timestamp(start)) - pd.DateOffset(days=15),
                    x1=pd.Timestamp(end) + pd.DateOffset(days=15),
                    fillcolor=dz.GOLD, opacity=.08, line_width=0,
                    annotation_text="12-month ranking window",
                    annotation_position="bottom right",
                    annotation_font=dict(size=11, color=dz.FAINT))
    f.add_hline(y=0, line=dict(color=dz.FAINT, width=1))
    events(f, label=True)
    f.update_xaxes(range=[pd.Timestamp(start) - pd.DateOffset(days=20),
                          pd.Timestamp(end) + pd.DateOffset(days=20)])
    f.update_yaxes(title="net tonnes since start of range" if running
                   else "tonnes / month (+ buy, − sell)")
    who = " and ".join(picked)
    f.update_layout(
        title=dict(text=f"{who}: "
                   + ("running total of net purchases" if running
                      else "monthly net purchases and sales")
                   + "<br><span style='font-size:11px'>sample data</span>",
                   font=dict(size=14), x=0, y=.98),
        margin=dict(t=78, b=46), barmode="group", bargap=.25,
        showlegend=len(picked) == 2, hovermode="x unified",
        # legend under the plot, clear of the event labels above it
        legend=dict(orientation="h", x=0, y=-0.1, yanchor="top",
                    font=dict(size=12)))
    chart(f, 430)

    span = (f"{pd.Timestamp(start).strftime('%b %Y')} to "
            f"{pd.Timestamp(end).strftime('%b %Y')}")
    for c in picked:
        d = sel[sel.country == c]
        tot = d.net_purchases_t.sum()
        big = d.loc[d.net_purchases_t.abs().idxmax()]
        st.markdown(
            f'<p class="facts"><b>{c}</b>: net {tot:+,.0f} t from {span}. '
            f'Bought in {(d.net_purchases_t > 0).sum()} of {len(d)} months, '
            f'sold in {(d.net_purchases_t < 0).sum()}. Largest month '
            f'{big.net_purchases_t:+,.1f} t in '
            f'{big.date.strftime("%b %Y")}.</p>', unsafe_allow_html=True)
    st.caption("The ranking above covers only the latest 12 months (shaded "
               "here). This view can cover the whole sample period, so its "
               "totals can differ from the ranking's. Positive months are "
               "net buying, negative months net selling. Event rules mark "
               "dates only; they do not show what caused a change.")

# ============================================================== INFERRED =====
with tabI:
    st.subheader("The gap")
    st.caption(f"How much official buying goes unreported each quarter? — "
               f"{gap.quarter_end.iloc[-1].to_period('Q')}")
    f = go.Figure()
    f.add_trace(go.Scatter(x=gap.quarter_end, y=gap.imf_reported_t,
        mode="lines", line=dict(width=0), hoverinfo="skip"))
    f.add_trace(go.Scatter(x=gap.quarter_end, y=gap.wgc_estimate_t,
        name="WGC estimate", mode="lines",
        line=dict(color=dz.MARK, width=1.6, dash=dz.DASH),
        fill="tonexty", fillcolor="rgba(163,120,10,.16)"))
    f.add_trace(go.Bar(x=gap.quarter_end, y=gap.imf_reported_t,
        name="reported to IMF", marker_color=dz.MARK, opacity=.85))
    events(f, label=True)
    endlabel(f, gap.quarter_end.iloc[-1], gap.wgc_estimate_t.iloc[-1],
             f"WGC <b>{gap.wgc_estimate_t.iloc[-1]:,.0f}</b> t")
    endlabel(f, gap.quarter_end.iloc[-1], gap.imf_reported_t.iloc[-1],
             f"IMF <b>{gap.imf_reported_t.iloc[-1]:,.0f}</b> t")
    f.update_yaxes(title="tonnes / quarter")
    chart(f, 430)
    st.caption("Bars: purchases reported to the IMF. Dashed: World Gold "
               "Council estimate of actual official demand. Shaded: the "
               "unreported residual.")

    st.subheader("Physical flow west to east")
    st.caption(f"Where are the bars going, and is the float being "
               f"replenished? — Swiss customs, {fmt(asof['swiss'])}")
    f = go.Figure()
    for dest in ["other", "UAE + Gulf", "UK + US", "Turkey", "India",
                 "China + HK"]:
        d = swiss[swiss.destination == dest]
        f.add_trace(go.Scatter(x=d.date, y=d.tonnes, name=dest,
            stackgroup="flow", mode="none", fillcolor=dz.hue(dest),
            hovertemplate=f"{dest}: %{{y:.0f}} t<extra></extra>"))
    events(f, label=False)
    show_repl = st.toggle("show mine replenishment")
    if show_repl:
        f.add_hline(y=dz.MINE_TOTAL_TPM,
            line=dict(color=dz.MARK, width=1.2, dash="dash"),
            annotation_text="all mine supply ≈ 300 t/mo",
            annotation_position="top left")
        f.add_hline(y=dz.MINE_WESTERN_TPM,
            line=dict(color=dz.MARK, width=1.2, dash="dot"),
            annotation_text="enters Western circuit ≈ 200 t/mo",
            annotation_position="bottom left")
    f.update_yaxes(title="tonnes / month", range=[0, 330])
    f.update_layout(showlegend=True, legend=dict(orientation="h", y=1.06,
        x=0, font=dict(size=12)), hovermode="x unified")
    chart(f, 400)
    if show_repl:
        st.caption("Output above the lower line drains the Western float "
                   "faster than the ground refills it. The space between the "
                   "lines is mine supply born outside the circuit (China, "
                   "Russia, Uzbekistan, Kazakhstan).")

st.caption("All figures on this page are sample data made by `ingest.py "
           "--synthetic` for practice. They are shaped like the real series "
           "but are not real prices, holdings or flows.")
st.caption("Sources when live: COMEX front-month futures (GC=F), FRED DFII10, "
           "GLD and IAU daily bar lists, IMF International Financial "
           "Statistics, World Gold Council Gold Demand Trends, Swiss-Impex "
           "tariff heading 7108. Event rules: Feb 22 reserve freeze, Jun 22 "
           "G7 import ban, Jun 25 Iran war, Nov 25 CBR sales begin, May 26 "
           "escalation.")
